# Generated by Django 4.0.4 on 2022-04-15 08:13

import cars.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('register_date', models.DateField()),
                ('total_income', models.IntegerField(default=0)),
                ('total_expenses', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_income', models.IntegerField(default=0)),
                ('total_expenses', models.IntegerField(default=0)),
                ('car', models.ForeignKey(default=cars.models.get_default_car, on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('income', models.IntegerField(default=0)),
                ('expenses', models.IntegerField(default=0)),
                ('month', models.ForeignKey(default=cars.models.get_default_month, on_delete=django.db.models.deletion.CASCADE, to='cars.month')),
            ],
        ),
    ]
