# Generated by Django 4.0.4 on 2022-04-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarDailyIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('income', models.IntegerField(default=0)),
                ('expenses', models.IntegerField(default=0)),
                ('car_slug', models.SlugField(blank=True, max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('date', models.DateTimeField(unique=True)),
                ('total_income', models.IntegerField(default=0)),
                ('total_expenses', models.IntegerField(default=0)),
                ('data', models.ManyToManyField(related_name='data', to='cars.cardailyincome')),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('date', models.DateTimeField(unique=True)),
                ('total_income', models.IntegerField(default=0)),
                ('total_expenses', models.IntegerField(default=0)),
                ('days', models.ManyToManyField(blank=True, related_name='days', to='cars.day')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('register_date', models.DateTimeField()),
                ('total_income', models.IntegerField(default=0)),
                ('total_expenses', models.IntegerField(default=0)),
                ('work_days', models.ManyToManyField(related_name='work_days', to='cars.day')),
                ('work_months', models.ManyToManyField(related_name='work_months', to='cars.month')),
            ],
        ),
    ]
