# Generated by Django 4.0.4 on 2022-04-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('date', models.DateTimeField(unique=True)),
                ('total_income', models.IntegerField()),
                ('total_expenses', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('date', models.DateTimeField(unique=True)),
                ('total_income', models.IntegerField()),
                ('total_expenses', models.IntegerField()),
                ('days', models.ManyToManyField(blank=True, related_name='days', to='cars.day')),
            ],
        ),
    ]
