# Generated by Django 4.0.4 on 2022-04-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardailyincome',
            name='car_slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
    ]
