# Generated by Django 4.0.4 on 2022-04-14 12:39

import cars.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_cardailyincome_car_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='month',
            field=models.ForeignKey(default=cars.models.get_default_month, on_delete=django.db.models.deletion.CASCADE, to='cars.month'),
        ),
    ]
