# Generated by Django 4.0.4 on 2022-04-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_rename_total_expenses_day_expenses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='month',
            name='date',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
