# Generated by Django 4.0.4 on 2022-04-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_day_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarMonthIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('income', models.IntegerField(default=0)),
                ('expenses', models.IntegerField(default=0)),
                ('car_slug', models.SlugField(blank=True, max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='month',
            name='data',
            field=models.ManyToManyField(related_name='data', to='cars.carmonthincome'),
        ),
    ]
