# Generated by Django 4.0.4 on 2022-04-14 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_carmonthincome_month_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='month',
            name='data',
        ),
        migrations.DeleteModel(
            name='CarMonthIncome',
        ),
    ]
