# Generated by Django 4.0.4 on 2022-04-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_day_date_alter_month_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='expenses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='day',
            name='income',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='month',
            name='total_expenses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='month',
            name='total_income',
            field=models.IntegerField(default=0),
        ),
    ]
