# Generated by Django 4.0.4 on 2022-04-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_remove_month_data_delete_carmonthincome'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardailyincome',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
