# Generated by Django 4.0.4 on 2022-04-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_day_expenses_alter_day_income_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='expenses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='income',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='work_days',
            field=models.ManyToManyField(blank=True, related_name='work_days', to='cars.day'),
        ),
    ]
