# Generated by Django 4.0.4 on 2022-04-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_car_expenses_car_income_car_work_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='months',
            field=models.ManyToManyField(blank=True, related_name='work_months', to='cars.month'),
        ),
        migrations.AlterField(
            model_name='car',
            name='register_date',
            field=models.DateTimeField(),
        ),
    ]
